### PR TITLE
Add swift package manager support

### PR DESCRIPTION
**Pull request by bitomule**
Now that Xcode 11 has support for swift package manager it'll be cool if TraktKit supported it. This PR adds the manifest file with some basic settings I think should be checked and tested.

Things to note:

- Including Common will be enough?
- Does TraktKit support all these platforms?

### CODE REVIEW

**Comment by moritzsternemann** [comment]
LGTM! 👍

**Comment by josh** [comment]
Just tested and it seems to work for me locally.

**Comment by bitomule** [comment]
@MaxHasADHD is this repo still active?

**Comment by MaxHasADHD** [comment]
Sorry, yes it is. It's been a bit busy for me. I'll try to look into this soon sorry!

**Comment by MaxHasADHD** [comment]
Merged another PR that added Swift PM support.

**Pull request closed without merging**
