### PR TITLE
Support CocoaPods & Carthage

### PR DESCRIPTION
**Pull request by filipejtdias**

### CODE REVIEW

**Comment by filipejtdias** [comment]
@MaxHasADHD any updates on this?

**Comment by MaxHasADHD** [comment]
@filipejtdias hey! Sorry, I will get to it this week. Had to put out some fires on my app.

**Comment by MaxHasADHD** [comment]
@filipejtdias I added the 1.0.0 tag to the repo! I will try linting again. If you could try too and confirm its working still, or get the same error I saw before that would be great 👍

**Comment by filipejtdias** [comment]
@MaxHasADHD 
Passed validation!
https://image.ibb.co/cZws27/Screen_Shot_2018_04_01_at_17_31_25.png

**Comment by MaxHasADHD** [comment]
Thanks @filipejtdias! I'll confirm I'm on the latest cocoa pods and check this out, and will hopefully merge it tonight. Sorry I've been slow 😅 It's been busy.

**Pull request merged**
