### PR TITLE
Support CocoaPods & Carthage

### PR DESCRIPTION
**Pull request by filipejtdias**
Hi!
This will only work if you create a tag "1.0.0" on master.
If you find any trouble to test, please let me know.

### CODE REVIEW

**Comment by MaxHasADHD** [comment]
This looks good! I will do some testing and get this merged in, thank you :)

**Comment by MaxHasADHD** [comment]
Can you update the `readme.md` with instructions of use

**Comment by filipejtdias** [comment]
Readme.md updated! You can consult this tutorial to publish properly the TraktKit pod.
[Release Pod Tutorial](https://guides.cocoapods.org/making/making-a-cocoapod.html)
After the PR merged, I think you can create the tag and push the podspec (`pod trunk push TraktKit.podspec`)

**Comment by MaxHasADHD** [comment]
So I merged it then tried to push but kept encountering issues. Will need to look into this more I suppose.

**Comment by MaxHasADHD** [comment]
I'm seeing ``` -> TraktKit (1.0.0)
    - WARN  | url: There was a problem validating the URL https://www.github.com/MaxHasADHD/TraktKit.
    - ERROR | [iOS] unknown: Encountered an unknown error (/usr/bin/xcrun simctl list -j devices```.

Can't find fix :/

**Comment by filipejtdias** [comment]
You don't have the tag created. Did you run the lint command?

**Comment by MaxHasADHD** [comment]
@filipejtdias I created / deleted the tag a few times, so when testing it was there. This is when running `pod spec lint` and I get errors for `pod lib lint` as well, passing in the local Podspec file. It doesn't like the HomePage URL, according to the URL. All forums I found on it had really no solution :/ I can create a new branch with the changes merged in and create the 1.0.0 tag again if it would show you the same thing?

**Comment by MaxHasADHD** [comment]
@filipejtdias when it was on your repo did linting work? what cocoa pods version were you on? I was on 1.4.0 I believe.

**Comment by filipejtdias** [comment]
Sorry Max for the delay. Yes, the lint worked with me and the cocoapods version was 1.4.0. Everything worked fine. Can you check if the Xcode Path location is well defined? If you run `xcode-select -p` on the terminal, the output should be something like this: `/Applications/Xcode.app/Contents/Developer`

**Comment by filipejtdias** [comment]
Any update on this?

**Comment by MaxHasADHD** [comment]
Hey @filipejtdias could you re-open a PR? I'll look into this tonight

**Comment by filipejtdias** [comment]
@MaxHasADHD Done: https://github.com/MaxHasADHD/TraktKit/pull/16

**Comment by pahnev** [comment]
@MaxHasADHD, if you’d add the 1.0 tag to the master branch, it would be easier for others to help. Once you’ve done it, you should have release in the https://github.com/MaxHasADHD/TraktKit/releases

**Pull request merged**
